sudo: required
services:
  - docker

before_install:
  - docker build -t mordred2000/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mordred2000/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  enc: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-818348878768"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"